// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { WriterVault$Type } from "./WriterVault";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["WriterVault"]: WriterVault$Type;
    ["contracts/WriterVault.sol:WriterVault"]: WriterVault$Type;
  }

  interface ContractTypesMap {
    ["WriterVault"]: GetContractReturnType<WriterVault$Type["abi"]>;
    ["contracts/WriterVault.sol:WriterVault"]: GetContractReturnType<WriterVault$Type["abi"]>;
  }
}
