/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { ITeller, ITellerInterface } from "../../interfaces/ITeller";

const _abi = [
  {
    inputs: [],
    name: "exchangeRate",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "usycAmount",
        type: "uint256",
      },
    ],
    name: "redeem",
    outputs: [
      {
        internalType: "uint256",
        name: "usdcAmount",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "subscribe",
    outputs: [
      {
        internalType: "uint256",
        name: "usycAmount",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "usdcAmount",
        type: "uint256",
      },
    ],
    name: "usdcToUsyc",
    outputs: [
      {
        internalType: "uint256",
        name: "usycAmount",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "usycAmount",
        type: "uint256",
      },
    ],
    name: "usycToUsdc",
    outputs: [
      {
        internalType: "uint256",
        name: "usdcAmount",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ITeller__factory {
  static readonly abi = _abi;
  static createInterface(): ITellerInterface {
    return new Interface(_abi) as ITellerInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ITeller {
    return new Contract(address, _abi, runner) as unknown as ITeller;
  }
}
