/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IWriterVault,
  IWriterVaultInterface,
} from "../../interfaces/IWriterVault";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "writer",
        type: "address",
      },
      {
        internalType: "string",
        name: "slug",
        type: "string",
      },
    ],
    name: "receivePayment",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IWriterVault__factory {
  static readonly abi = _abi;
  static createInterface(): IWriterVaultInterface {
    return new Interface(_abi) as IWriterVaultInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IWriterVault {
    return new Contract(address, _abi, runner) as unknown as IWriterVault;
  }
}
