// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IWriterVault$Type } from "./IWriterVault";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IWriterVault"]: IWriterVault$Type;
    ["contracts/interfaces/IWriterVault.sol:IWriterVault"]: IWriterVault$Type;
  }

  interface ContractTypesMap {
    ["IWriterVault"]: GetContractReturnType<IWriterVault$Type["abi"]>;
    ["contracts/interfaces/IWriterVault.sol:IWriterVault"]: GetContractReturnType<IWriterVault$Type["abi"]>;
  }
}
