// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IWriterVault$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IWriterVault",
  "sourceName": "contracts/interfaces/IWriterVault.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "writer",
          "type": "address"
        },
        {
          "internalType": "string",
          "name": "slug",
          "type": "string"
        },
        {
          "internalType": "enum IWriterVault.PaymentType",
          "name": "pType",
          "type": "uint8"
        }
      ],
      "name": "receivePayment",
      "outputs": [],
      "stateMutability": "payable",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IWriterVault",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IWriterVault$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/interfaces/IWriterVault.sol:IWriterVault",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IWriterVault$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IWriterVault",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IWriterVault$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/interfaces/IWriterVault.sol:IWriterVault",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IWriterVault$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IWriterVault",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IWriterVault$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/interfaces/IWriterVault.sol:IWriterVault",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IWriterVault$Type["abi"]>>;
}
