// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IUSYC$Type } from "./IUSYC";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IUSYC"]: IUSYC$Type;
    ["contracts/interfaces/IUSYC.sol:IUSYC"]: IUSYC$Type;
  }

  interface ContractTypesMap {
    ["IUSYC"]: GetContractReturnType<IUSYC$Type["abi"]>;
    ["contracts/interfaces/IUSYC.sol:IUSYC"]: GetContractReturnType<IUSYC$Type["abi"]>;
  }
}
