// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { MockTeller$Type } from "./MockTeller";
import { MockUSYC$Type } from "./MockUSYC";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MockTeller"]: MockTeller$Type;
    ["MockUSYC"]: MockUSYC$Type;
    ["contracts/MockTeller.sol:MockTeller"]: MockTeller$Type;
    ["contracts/MockTeller.sol:MockUSYC"]: MockUSYC$Type;
  }

  interface ContractTypesMap {
    ["MockTeller"]: GetContractReturnType<MockTeller$Type["abi"]>;
    ["MockUSYC"]: GetContractReturnType<MockUSYC$Type["abi"]>;
    ["contracts/MockTeller.sol:MockTeller"]: GetContractReturnType<MockTeller$Type["abi"]>;
    ["contracts/MockTeller.sol:MockUSYC"]: GetContractReturnType<MockUSYC$Type["abi"]>;
  }
}
