// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface ITeller$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "ITeller",
  "sourceName": "contracts/interfaces/ITeller.sol",
  "abi": [
    {
      "inputs": [],
      "name": "exchangeRate",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "usycAmount",
          "type": "uint256"
        }
      ],
      "name": "redeem",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "usdcAmount",
          "type": "uint256"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "subscribe",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "usycAmount",
          "type": "uint256"
        }
      ],
      "stateMutability": "payable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "usdcAmount",
          "type": "uint256"
        }
      ],
      "name": "usdcToUsyc",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "usycAmount",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "usycAmount",
          "type": "uint256"
        }
      ],
      "name": "usycToUsdc",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "usdcAmount",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "ITeller",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ITeller$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/interfaces/ITeller.sol:ITeller",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ITeller$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "ITeller",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ITeller$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/interfaces/ITeller.sol:ITeller",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ITeller$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "ITeller",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ITeller$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/interfaces/ITeller.sol:ITeller",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ITeller$Type["abi"]>>;
}
