// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ReaderVault$Type } from "./ReaderVault";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ReaderVault"]: ReaderVault$Type;
    ["contracts/ReaderVault.sol:ReaderVault"]: ReaderVault$Type;
  }

  interface ContractTypesMap {
    ["ReaderVault"]: GetContractReturnType<ReaderVault$Type["abi"]>;
    ["contracts/ReaderVault.sol:ReaderVault"]: GetContractReturnType<ReaderVault$Type["abi"]>;
  }
}
