/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ITeller } from "./ITeller";
export type { IUSYC } from "./IUSYC";
export type { IWriterVault } from "./IWriterVault";
