/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iTellerSol from "./ITeller.sol";
export type { iTellerSol };
export type { IUSYC } from "./IUSYC";
export type { IWriterVault } from "./IWriterVault";
