/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ITellerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "exchangeRate"
      | "redeem"
      | "subscribe"
      | "usdcToUsyc"
      | "usycToUsdc"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "exchangeRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "redeem",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "subscribe", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "usdcToUsyc",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "usycToUsdc",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "exchangeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "redeem", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "subscribe", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdcToUsyc", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usycToUsdc", data: BytesLike): Result;
}

export interface ITeller extends BaseContract {
  connect(runner?: ContractRunner | null): ITeller;
  waitForDeployment(): Promise<this>;

  interface: ITellerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  exchangeRate: TypedContractMethod<[], [bigint], "view">;

  redeem: TypedContractMethod<
    [usycAmount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  subscribe: TypedContractMethod<[], [bigint], "payable">;

  usdcToUsyc: TypedContractMethod<[usdcAmount: BigNumberish], [bigint], "view">;

  usycToUsdc: TypedContractMethod<[usycAmount: BigNumberish], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "exchangeRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "redeem"
  ): TypedContractMethod<[usycAmount: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "subscribe"
  ): TypedContractMethod<[], [bigint], "payable">;
  getFunction(
    nameOrSignature: "usdcToUsyc"
  ): TypedContractMethod<[usdcAmount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "usycToUsdc"
  ): TypedContractMethod<[usycAmount: BigNumberish], [bigint], "view">;

  filters: {};
}
