/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "ITeller",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ITeller__factory>;
    getContractFactory(
      name: "IUSYC",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IUSYC__factory>;
    getContractFactory(
      name: "IWriterVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IWriterVault__factory>;
    getContractFactory(
      name: "ReaderVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ReaderVault__factory>;
    getContractFactory(
      name: "WriterVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.WriterVault__factory>;

    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "ITeller",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ITeller>;
    getContractAt(
      name: "IUSYC",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IUSYC>;
    getContractAt(
      name: "IWriterVault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IWriterVault>;
    getContractAt(
      name: "ReaderVault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ReaderVault>;
    getContractAt(
      name: "WriterVault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.WriterVault>;

    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "ITeller",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ITeller>;
    deployContract(
      name: "IUSYC",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IUSYC>;
    deployContract(
      name: "IWriterVault",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IWriterVault>;
    deployContract(
      name: "ReaderVault",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReaderVault>;
    deployContract(
      name: "WriterVault",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.WriterVault>;

    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "ITeller",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ITeller>;
    deployContract(
      name: "IUSYC",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IUSYC>;
    deployContract(
      name: "IWriterVault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IWriterVault>;
    deployContract(
      name: "ReaderVault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReaderVault>;
    deployContract(
      name: "WriterVault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.WriterVault>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
