/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface MockTellerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "exchangeRate"
      | "redeem"
      | "subscribe"
      | "usdcToUsyc"
      | "usycBalance"
      | "usycToUsdc"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Redeemed" | "Subscribed"): EventFragment;

  encodeFunctionData(
    functionFragment: "exchangeRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "redeem",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "subscribe", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "usdcToUsyc",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "usycBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "usycToUsdc",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "exchangeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "redeem", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "subscribe", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdcToUsyc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "usycBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usycToUsdc", data: BytesLike): Result;
}

export namespace RedeemedEvent {
  export type InputTuple = [
    caller: AddressLike,
    usycIn: BigNumberish,
    usdcOut: BigNumberish
  ];
  export type OutputTuple = [caller: string, usycIn: bigint, usdcOut: bigint];
  export interface OutputObject {
    caller: string;
    usycIn: bigint;
    usdcOut: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscribedEvent {
  export type InputTuple = [
    caller: AddressLike,
    usdcIn: BigNumberish,
    usycOut: BigNumberish
  ];
  export type OutputTuple = [caller: string, usdcIn: bigint, usycOut: bigint];
  export interface OutputObject {
    caller: string;
    usdcIn: bigint;
    usycOut: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockTeller extends BaseContract {
  connect(runner?: ContractRunner | null): MockTeller;
  waitForDeployment(): Promise<this>;

  interface: MockTellerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  exchangeRate: TypedContractMethod<[], [bigint], "view">;

  redeem: TypedContractMethod<
    [usycAmount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  subscribe: TypedContractMethod<[], [bigint], "payable">;

  usdcToUsyc: TypedContractMethod<[usdcAmount: BigNumberish], [bigint], "view">;

  usycBalance: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  usycToUsdc: TypedContractMethod<[usycAmount: BigNumberish], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "exchangeRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "redeem"
  ): TypedContractMethod<[usycAmount: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "subscribe"
  ): TypedContractMethod<[], [bigint], "payable">;
  getFunction(
    nameOrSignature: "usdcToUsyc"
  ): TypedContractMethod<[usdcAmount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "usycBalance"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "usycToUsdc"
  ): TypedContractMethod<[usycAmount: BigNumberish], [bigint], "view">;

  getEvent(
    key: "Redeemed"
  ): TypedContractEvent<
    RedeemedEvent.InputTuple,
    RedeemedEvent.OutputTuple,
    RedeemedEvent.OutputObject
  >;
  getEvent(
    key: "Subscribed"
  ): TypedContractEvent<
    SubscribedEvent.InputTuple,
    SubscribedEvent.OutputTuple,
    SubscribedEvent.OutputObject
  >;

  filters: {
    "Redeemed(address,uint256,uint256)": TypedContractEvent<
      RedeemedEvent.InputTuple,
      RedeemedEvent.OutputTuple,
      RedeemedEvent.OutputObject
    >;
    Redeemed: TypedContractEvent<
      RedeemedEvent.InputTuple,
      RedeemedEvent.OutputTuple,
      RedeemedEvent.OutputObject
    >;

    "Subscribed(address,uint256,uint256)": TypedContractEvent<
      SubscribedEvent.InputTuple,
      SubscribedEvent.OutputTuple,
      SubscribedEvent.OutputObject
    >;
    Subscribed: TypedContractEvent<
      SubscribedEvent.InputTuple,
      SubscribedEvent.OutputTuple,
      SubscribedEvent.OutputObject
    >;
  };
}
