/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ReaderVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "FLOAT_AMOUNT"
      | "PLATFORM_FEE"
      | "balanceOf"
      | "deposit"
      | "owner"
      | "payForClap"
      | "payForComment"
      | "payForRead"
      | "teller"
      | "usdcFloat"
      | "usycStaked"
      | "usycToken"
      | "withdraw"
      | "writerVault"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ArticleRead"
      | "ClapPaid"
      | "CommentPaid"
      | "Deposited"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "FLOAT_AMOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PLATFORM_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "deposit", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payForClap",
    values: [AddressLike, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "payForComment",
    values: [AddressLike, AddressLike, string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "payForRead",
    values: [AddressLike, AddressLike, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "teller", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "usdcFloat",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "usycStaked",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usycToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "writerVault",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "FLOAT_AMOUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PLATFORM_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payForClap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "payForComment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "payForRead", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "teller", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdcFloat", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usycStaked", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usycToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "writerVault",
    data: BytesLike
  ): Result;
}

export namespace ArticleReadEvent {
  export type InputTuple = [
    reader: AddressLike,
    writer: AddressLike,
    slug: string,
    usdcPaid: BigNumberish
  ];
  export type OutputTuple = [
    reader: string,
    writer: string,
    slug: string,
    usdcPaid: bigint
  ];
  export interface OutputObject {
    reader: string;
    writer: string;
    slug: string;
    usdcPaid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClapPaidEvent {
  export type InputTuple = [
    reader: AddressLike,
    writer: AddressLike,
    slug: string,
    usdcPaid: BigNumberish
  ];
  export type OutputTuple = [
    reader: string,
    writer: string,
    slug: string,
    usdcPaid: bigint
  ];
  export interface OutputObject {
    reader: string;
    writer: string;
    slug: string;
    usdcPaid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CommentPaidEvent {
  export type InputTuple = [
    reader: AddressLike,
    writer: AddressLike,
    slug: string,
    usdcPaid: BigNumberish,
    commentHash: string
  ];
  export type OutputTuple = [
    reader: string,
    writer: string,
    slug: string,
    usdcPaid: bigint,
    commentHash: string
  ];
  export interface OutputObject {
    reader: string;
    writer: string;
    slug: string;
    usdcPaid: bigint;
    commentHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositedEvent {
  export type InputTuple = [
    reader: AddressLike,
    usdcAmount: BigNumberish,
    usycMinted: BigNumberish
  ];
  export type OutputTuple = [
    reader: string,
    usdcAmount: bigint,
    usycMinted: bigint
  ];
  export interface OutputObject {
    reader: string;
    usdcAmount: bigint;
    usycMinted: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [reader: AddressLike, usdcAmount: BigNumberish];
  export type OutputTuple = [reader: string, usdcAmount: bigint];
  export interface OutputObject {
    reader: string;
    usdcAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReaderVault extends BaseContract {
  connect(runner?: ContractRunner | null): ReaderVault;
  waitForDeployment(): Promise<this>;

  interface: ReaderVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  FLOAT_AMOUNT: TypedContractMethod<[], [bigint], "view">;

  PLATFORM_FEE: TypedContractMethod<[], [bigint], "view">;

  balanceOf: TypedContractMethod<
    [reader: AddressLike],
    [
      [bigint, bigint, bigint] & {
        usdcBalance: bigint;
        usycBalance: bigint;
        estimatedUsdcValue: bigint;
      }
    ],
    "view"
  >;

  deposit: TypedContractMethod<[], [void], "payable">;

  owner: TypedContractMethod<[], [string], "view">;

  payForClap: TypedContractMethod<
    [reader: AddressLike, writer: AddressLike, slug: string],
    [void],
    "nonpayable"
  >;

  payForComment: TypedContractMethod<
    [
      reader: AddressLike,
      writer: AddressLike,
      slug: string,
      price: BigNumberish,
      commentHash: string
    ],
    [void],
    "nonpayable"
  >;

  payForRead: TypedContractMethod<
    [
      reader: AddressLike,
      writer: AddressLike,
      slug: string,
      price: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  teller: TypedContractMethod<[], [string], "view">;

  usdcFloat: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  usycStaked: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  usycToken: TypedContractMethod<[], [string], "view">;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  writerVault: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "FLOAT_AMOUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PLATFORM_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<
    [reader: AddressLike],
    [
      [bigint, bigint, bigint] & {
        usdcBalance: bigint;
        usycBalance: bigint;
        estimatedUsdcValue: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payForClap"
  ): TypedContractMethod<
    [reader: AddressLike, writer: AddressLike, slug: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "payForComment"
  ): TypedContractMethod<
    [
      reader: AddressLike,
      writer: AddressLike,
      slug: string,
      price: BigNumberish,
      commentHash: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "payForRead"
  ): TypedContractMethod<
    [
      reader: AddressLike,
      writer: AddressLike,
      slug: string,
      price: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "teller"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "usdcFloat"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "usycStaked"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "usycToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "writerVault"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "ArticleRead"
  ): TypedContractEvent<
    ArticleReadEvent.InputTuple,
    ArticleReadEvent.OutputTuple,
    ArticleReadEvent.OutputObject
  >;
  getEvent(
    key: "ClapPaid"
  ): TypedContractEvent<
    ClapPaidEvent.InputTuple,
    ClapPaidEvent.OutputTuple,
    ClapPaidEvent.OutputObject
  >;
  getEvent(
    key: "CommentPaid"
  ): TypedContractEvent<
    CommentPaidEvent.InputTuple,
    CommentPaidEvent.OutputTuple,
    CommentPaidEvent.OutputObject
  >;
  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "ArticleRead(address,address,string,uint256)": TypedContractEvent<
      ArticleReadEvent.InputTuple,
      ArticleReadEvent.OutputTuple,
      ArticleReadEvent.OutputObject
    >;
    ArticleRead: TypedContractEvent<
      ArticleReadEvent.InputTuple,
      ArticleReadEvent.OutputTuple,
      ArticleReadEvent.OutputObject
    >;

    "ClapPaid(address,address,string,uint256)": TypedContractEvent<
      ClapPaidEvent.InputTuple,
      ClapPaidEvent.OutputTuple,
      ClapPaidEvent.OutputObject
    >;
    ClapPaid: TypedContractEvent<
      ClapPaidEvent.InputTuple,
      ClapPaidEvent.OutputTuple,
      ClapPaidEvent.OutputObject
    >;

    "CommentPaid(address,address,string,uint256,string)": TypedContractEvent<
      CommentPaidEvent.InputTuple,
      CommentPaidEvent.OutputTuple,
      CommentPaidEvent.OutputObject
    >;
    CommentPaid: TypedContractEvent<
      CommentPaidEvent.InputTuple,
      CommentPaidEvent.OutputTuple,
      CommentPaidEvent.OutputObject
    >;

    "Deposited(address,uint256,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "Withdrawn(address,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
