/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface WriterVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "earningsOf"
      | "owner"
      | "receivePayment"
      | "teller"
      | "totalClaps"
      | "totalComments"
      | "totalReads"
      | "totalUsdcEarned"
      | "usycBalance"
      | "usycToken"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "EarningsReceived" | "EarningsWithdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "earningsOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "receivePayment",
    values: [AddressLike, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "teller", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalClaps",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalComments",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalReads",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalUsdcEarned",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "usycBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usycToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(functionFragment: "earningsOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "receivePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "teller", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "totalClaps", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalComments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalReads", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalUsdcEarned",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "usycBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usycToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace EarningsReceivedEvent {
  export type InputTuple = [
    writer: AddressLike,
    usdcAmount: BigNumberish,
    usycMinted: BigNumberish,
    slug: string,
    pType: BigNumberish
  ];
  export type OutputTuple = [
    writer: string,
    usdcAmount: bigint,
    usycMinted: bigint,
    slug: string,
    pType: bigint
  ];
  export interface OutputObject {
    writer: string;
    usdcAmount: bigint;
    usycMinted: bigint;
    slug: string;
    pType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EarningsWithdrawnEvent {
  export type InputTuple = [writer: AddressLike, usdcAmount: BigNumberish];
  export type OutputTuple = [writer: string, usdcAmount: bigint];
  export interface OutputObject {
    writer: string;
    usdcAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface WriterVault extends BaseContract {
  connect(runner?: ContractRunner | null): WriterVault;
  waitForDeployment(): Promise<this>;

  interface: WriterVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  earningsOf: TypedContractMethod<
    [writer: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        usyc: bigint;
        estimatedUsdc: bigint;
        reads: bigint;
        claps: bigint;
        comments: bigint;
        lifetimeUsdc: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  receivePayment: TypedContractMethod<
    [writer: AddressLike, slug: string, pType: BigNumberish],
    [void],
    "payable"
  >;

  teller: TypedContractMethod<[], [string], "view">;

  totalClaps: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  totalComments: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  totalReads: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  totalUsdcEarned: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  usycBalance: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  usycToken: TypedContractMethod<[], [string], "view">;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "earningsOf"
  ): TypedContractMethod<
    [writer: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        usyc: bigint;
        estimatedUsdc: bigint;
        reads: bigint;
        claps: bigint;
        comments: bigint;
        lifetimeUsdc: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "receivePayment"
  ): TypedContractMethod<
    [writer: AddressLike, slug: string, pType: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "teller"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalClaps"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalComments"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalReads"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalUsdcEarned"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "usycBalance"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "usycToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "EarningsReceived"
  ): TypedContractEvent<
    EarningsReceivedEvent.InputTuple,
    EarningsReceivedEvent.OutputTuple,
    EarningsReceivedEvent.OutputObject
  >;
  getEvent(
    key: "EarningsWithdrawn"
  ): TypedContractEvent<
    EarningsWithdrawnEvent.InputTuple,
    EarningsWithdrawnEvent.OutputTuple,
    EarningsWithdrawnEvent.OutputObject
  >;

  filters: {
    "EarningsReceived(address,uint256,uint256,string,uint8)": TypedContractEvent<
      EarningsReceivedEvent.InputTuple,
      EarningsReceivedEvent.OutputTuple,
      EarningsReceivedEvent.OutputObject
    >;
    EarningsReceived: TypedContractEvent<
      EarningsReceivedEvent.InputTuple,
      EarningsReceivedEvent.OutputTuple,
      EarningsReceivedEvent.OutputObject
    >;

    "EarningsWithdrawn(address,uint256)": TypedContractEvent<
      EarningsWithdrawnEvent.InputTuple,
      EarningsWithdrawnEvent.OutputTuple,
      EarningsWithdrawnEvent.OutputObject
    >;
    EarningsWithdrawn: TypedContractEvent<
      EarningsWithdrawnEvent.InputTuple,
      EarningsWithdrawnEvent.OutputTuple,
      EarningsWithdrawnEvent.OutputObject
    >;
  };
}
